### ISSUE TITLE
Getting a Optional Parameter not allowed: Invalid option qos_time_to_live

### ISSUE THREAD

**Issue by kesbeast23** [jookies/jasmin#1094]
I am trying to connect to a new provider and am getting the following error.Optional Parameter not allowed: Invalid option qos_time_to_live
`2022-12-05 13:45:55 WARNING  1 Requesting bind as transceiver
2022-12-05 13:45:55 WARNING  1 Bind succeeded...now in state SMPPSessionStates.BOUND_TRX
2022-12-05 13:55:31 ERROR    1 Optional Parameter not allowed: Invalid option qos_time_to_live
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/smpp/twisted/protocol.py", line 211, in rawMessageReceived
    pdu = self.encoder.decode(BytesIO(message))
  File "/usr/local/lib/python3.10/site-packages/smpp/pdu/pdu_encoding.py", line 1038, in decode
    self.decodeBody(file, pdu, headerParams['command_length'] - self.HEADER_LEN)
  File "/usr/local/lib/python3.10/site-packages/smpp/pdu/pdu_encoding.py", line 1084, in decodeBody
    optionalParams = self.decodeOptionalParams(pdu.optionalParams, file, bodyLength - mParamsLen)
  File "/usr/local/lib/python3.10/site-packages/smpp/pdu/pdu_encoding.py", line 1180, in decodeOptionalParams
    raise PDUParseError("Invalid option %s" % optionName, pdu_types.CommandStatus.ESME_ROPTPARNOTALLWD)
smpp.pdu.error.PDUParseError: Optional Parameter not allowed: Invalid option qos_time_to_live
2022-12-05 13:55:31 CRITICAL 1 Received unparsable PDU b'0000003d0000000500000000000000170001013236373735373336343534000301313634363800000000000000000000045465737400170004638f49d3'
2022-12-05 13:55:40 ERROR    1 Optional Parameter not allowed: Invalid option qos_time_to_live
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/smpp/twisted/protocol.py", line 211, in rawMessageReceived
    pdu = self.encoder.decode(BytesIO(message))
  File "/usr/local/lib/python3.10/site-packages/smpp/pdu/pdu_encoding.py", line 1038, in decode
    self.decodeBody(file, pdu, headerParams['command_length'] - self.HEADER_LEN)
  File "/usr/local/lib/python3.10/site-packages/smpp/pdu/pdu_encoding.py", line 1084, in decodeBody
    optionalParams = self.decodeOptionalParams(pdu.optionalParams, file, bodyLength - mParamsLen)
  File "/usr/local/lib/python3.10/site-packages/smpp/pdu/pdu_encoding.py", line 1180, in decodeOptionalParams
    raise PDUParseError("Invalid option %s" % optionName, pdu_types.CommandStatus.ESME_ROPTPARNOTALLWD)
smpp.pdu.error.PDUParseError: Optional Parameter not allowed: Invalid option qos_time_to_live
2022-12-05 13:55:40 CRITICAL 1 Received unparsable PDU b'0000003d0000000500000000000000180001013236373735373336343534000301313634363800000000000000000000045465737400170004638f49db'
2022-12-05 13:55:47 ERROR    1 Optional Parameter not allowed: Invalid option qos_time_to_live
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/smpp/twisted/protocol.py", line 211, in rawMessageReceived
    pdu = self.encoder.decode(BytesIO(message))
  File "/usr/local/lib/python3.10/site-packages/smpp/pdu/pdu_encoding.py", line 1038, in decode
    self.decodeBody(file, pdu, headerParams['command_length'] - self.HEADER_LEN)
  File "/usr/local/lib/python3.10/site-packages/smpp/pdu/pdu_encoding.py", line 1084, in decodeBody
    optionalParams = self.decodeOptionalParams(pdu.optionalParams, file, bodyLength - mParamsLen)
  File "/usr/local/lib/python3.10/site-packages/smpp/pdu/pdu_encoding.py", line 1180, in decodeOptionalParams
    raise PDUParseError("Invalid option %s" % optionName, pdu_types.CommandStatus.ESME_ROPTPARNOTALLWD)
smpp.pdu.error.PDUParseError: Optional Parameter not allowed: Invalid option qos_time_to_live
2022-12-05 13:55:47 CRITICAL 1 Received unparsable PDU b'0000003d0000000500000000000000190001013236373735373336343534000301313634363800000000000000000000045465737400170004638f49e3'`

**Comment by JosephMasole** [comment]
> I am trying to connect to a new provider and am getting the following error.Optional Parameter not allowed: Invalid option qos_time_to_live
> `2022-12-05 13:45:55 WARNING  1 Requesting bind as transceiver
> 2022-12-05 13:45:55 WARNING  1 Bind succeeded...now in state SMPPSessionStates.BOUND_TRX
> 2022-12-05 13:55:31 ERROR    1 Optional Parameter not allowed: Invalid option qos_time_to_live
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/smpp/twisted/protocol.py", line 211, in rawMessageReceived
>     pdu = self.encoder.decode(BytesIO(message))
>   File "/usr/local/lib/python3.10/site-packages/smpp/pdu/pdu_encoding.py", line 1038, in decode
>     self.decodeBody(file, pdu, headerParams['command_length'] - self.HEADER_LEN)
>   File "/usr/local/lib/python3.10/site-packages/smpp/pdu/pdu_encoding.py", line 1084, in decodeBody
>     optionalParams = self.decodeOptionalParams(pdu.optionalParams, file, bodyLength - mParamsLen)
>   File "/usr/local/lib/python3.10/site-packages/smpp/pdu/pdu_encoding.py", line 1180, in decodeOptionalParams
>     raise PDUParseError("Invalid option %s" % optionName, pdu_types.CommandStatus.ESME_ROPTPARNOTALLWD)
> smpp.pdu.error.PDUParseError: Optional Parameter not allowed: Invalid option qos_time_to_live
> 2022-12-05 13:55:31 CRITICAL 1 Received unparsable PDU b'0000003d0000000500000000000000170001013236373735373336343534000301313634363800000000000000000000045465737400170004638f49d3'
> 2022-12-05 13:55:40 ERROR    1 Optional Parameter not allowed: Invalid option qos_time_to_live
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/smpp/twisted/protocol.py", line 211, in rawMessageReceived
>     pdu = self.encoder.decode(BytesIO(message))
>   File "/usr/local/lib/python3.10/site-packages/smpp/pdu/pdu_encoding.py", line 1038, in decode
>     self.decodeBody(file, pdu, headerParams['command_length'] - self.HEADER_LEN)
>   File "/usr/local/lib/python3.10/site-packages/smpp/pdu/pdu_encoding.py", line 1084, in decodeBody
>     optionalParams = self.decodeOptionalParams(pdu.optionalParams, file, bodyLength - mParamsLen)
>   File "/usr/local/lib/python3.10/site-packages/smpp/pdu/pdu_encoding.py", line 1180, in decodeOptionalParams
>     raise PDUParseError("Invalid option %s" % optionName, pdu_types.CommandStatus.ESME_ROPTPARNOTALLWD)
> smpp.pdu.error.PDUParseError: Optional Parameter not allowed: Invalid option qos_time_to_live
> 2022-12-05 13:55:40 CRITICAL 1 Received unparsable PDU b'0000003d0000000500000000000000180001013236373735373336343534000301313634363800000000000000000000045465737400170004638f49db'
> 2022-12-05 13:55:47 ERROR    1 Optional Parameter not allowed: Invalid option qos_time_to_live
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/smpp/twisted/protocol.py", line 211, in rawMessageReceived
>     pdu = self.encoder.decode(BytesIO(message))
>   File "/usr/local/lib/python3.10/site-packages/smpp/pdu/pdu_encoding.py", line 1038, in decode
>     self.decodeBody(file, pdu, headerParams['command_length'] - self.HEADER_LEN)
>   File "/usr/local/lib/python3.10/site-packages/smpp/pdu/pdu_encoding.py", line 1084, in decodeBody
>     optionalParams = self.decodeOptionalParams(pdu.optionalParams, file, bodyLength - mParamsLen)
>   File "/usr/local/lib/python3.10/site-packages/smpp/pdu/pdu_encoding.py", line 1180, in decodeOptionalParams
>     raise PDUParseError("Invalid option %s" % optionName, pdu_types.CommandStatus.ESME_ROPTPARNOTALLWD)
> smpp.pdu.error.PDUParseError: Optional Parameter not allowed: Invalid option qos_time_to_live
> 2022-12-05 13:55:47 CRITICAL 1 Received unparsable PDU b'0000003d0000000500000000000000190001013236373735373336343534000301313634363800000000000000000000045465737400170004638f49e3'`

Hi, I'm experiencing the same problem. Did you ever find a solution to this?
