### ISSUE TITLE
error: Could not find suitable distribution for Requirement.parse('zope-interface>=5')

### ISSUE THREAD

**Issue by edge-servers** [jookies/jasmin#1171]
While running python setup.py install i am facing this problem. 

python --version
Python 3.10.12

```
Processing dependencies for jasmin==0.11.0
Searching for zope-interface>=5
Reading https://pypi.org/simple/zope-interface/
/home/Projects/jasmin_project/venv/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
No local packages or working download links found for zope-interface>=5
error: Could not find suitable distribution for Requirement.parse('zope-interface>=5')
```
Already i have installed updated version of zope-interface 

```
(venv) smsc@in-pun:~/Projects/jasmin_project/jasmin-sms-gateway$ pip list
Package            Version
------------------ ----------
amqp               5.2.0
async-timeout      4.0.3
attrs              23.2.0
Automat            22.10.0
billiard           4.2.0
celery             5.3.6
certifi            2023.11.17
cffi               1.16.0
charset-normalizer 3.3.2
click              8.1.7
click-didyoumean   0.3.0
click-plugins      1.1.1
click-repl         0.3.0
constantly         23.10.4
cryptography       41.0.7
falcon             3.1.3
hyperlink          21.0.0
idna               3.6
incremental        22.10.0
jasmin             0.11.0
kombu              5.3.4
lockfile           0.12.2
pip                23.3.2
prometheus-client  0.18.0
prompt-toolkit     3.0.43
pyasn1             0.5.1
pyasn1-modules     0.3.0
pycparser          2.21
pyOpenSSL          23.3.0
pyparsing          3.1.1
python-dateutil    2.8.2
python-messaging   0.5.13
python-mimeparse   1.6.0
redis              5.0.1
requests           2.31.0
service-identity   23.1.0
setuptools         65.0.0
six                1.16.0
smpp.pdu3          0.6
smpp.twisted3      0.8
tabulate           0.8.10
treq               23.11.0
Twisted            23.10.0
txAMQP3            0.9.4
txredisapi         1.4.10
typing_extensions  4.9.0
tzdata             2023.4
urllib3            2.1.0
vine               5.1.0
wcwidth            0.2.13
wheel              0.42.0
zope.interface     6.1
```

Any suggestion @farirat 
Thanks in advance

**Comment by edge-servers** [comment]
```
sudo /usr/local/bin/jasmind.py --username jcliadmin --password jclipwd
Traceback (most recent call last):
  File "/usr/local/bin/jasmind.py", line 4, in <module>
    __import__('pkg_resources').run_script('jasmin==0.11.0', 'jasmind.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3267, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3241, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'zope-interface>=5' distribution was not found and is required by twisted, Twisted

```

**Comment by BlackOrder** [comment]
python 3.10.12 >> jasmin 0.10.12

jasmin 0.11.0 pumped to python 3.11
