### ISSUE TITLE
Kubernetes, can't run image from docker: AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by keffadi** [jookies/jasmin#1177]
this is what is printed when i run like Kind: deployment in kubernete cluster

Cleaning lock files
Starting interceptord
Starting jasmind
Traceback (most recent call last):
  File "/usr/local/bin/interceptord.py", line 15, in <module>
    from jasmin.interceptor.configs import InterceptorPBConfig
  File "/usr/local/lib/python3.11/site-packages/jasmin/__init__.py", line 33, in <module>
    if len(_r.groups()) == 2 and int(_r.group(2)) == 0:
           ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'groups'
Traceback (most recent call last):
  File "/usr/local/bin/jasmind.py", line 17, in <module>
    from jasmin.interceptor.configs import InterceptorPBClientConfig
  File "/usr/local/lib/python3.11/site-packages/jasmin/__init__.py", line 33, in <module>
    if len(_r.groups()) == 2 and int(_r.group(2)) == 0:
           ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'groups'

CAN YOU ADVISE PLEASE

**Comment by lauer** [comment]
Same error here. Did you find any solution?

**Comment by lauer** [comment]
Okay, I did some research, and in my deployment is called `jasmin-uat`, then the hostname is  `jasmin-uat-0` in the pod, which made the regex code in init.py fails. 

It worked again, when overwrite the HOSTNAME in env definition to just `jasmin-0`

But I would be nice if this line was fixed to support hostnames with multi `-`.

https://github.com/jookies/jasmin/blob/8455c1b875d5f22069759e8fbefcb7437c47db4b/jasmin/__init__.py#L32
