### ISSUE TITLE
Jasmin Instance got crash ERROR : "builtins.ValueError: ('Stumped', b'\xec')"

### ISSUE THREAD

**Issue by bss-haresh-makwana** [jookies/jasmin#1184]
Dear Team,

Please find attached log of jasmin. Application got crash and raised error. Request to help for same.

We are using Jasmin Version : 0.10.12.

 

LOGS:

==========================================================================

2024-03-05T10:24:56.247Z | Cleaning lock files

2024-03-05T10:24:56.252Z | Copy Conf file

2024-03-05T10:24:56.323Z | Starting jasmind

2024-03-05T10:24:57.516Z | 2024-03-05 10:24:57 INFO     1 Starting Jasmin Daemon ...

2024-03-05T10:24:57.517Z | 2024-03-05 10:24:57 INFO     1   Interceptor client Started.

2024-03-05T10:24:57.562Z | 2024-03-05 10:24:57 INFO     1   RedisClient Started.

2024-03-05T10:24:57.635Z | 2024-03-05 10:24:57 INFO     1   AMQP Broker Started.

2024-03-05T10:24:57.663Z | 2024-03-05 10:24:57 INFO     1   RouterPB Started.

2024-03-05T10:24:57.669Z | 2024-03-05 10:24:57 INFO     1   SMPPClientManagerPB Started.

2024-03-05T10:24:57.674Z | 2024-03-05 10:24:57 INFO     1   SMPPServer Started.

2024-03-05T10:24:57.679Z | 2024-03-05 10:24:57 INFO     1   SMPPServer Started.

2024-03-05T10:24:57.691Z | 2024-03-05 10:24:57 INFO     1   deliverSmThrower Started.

2024-03-05T10:24:57.699Z | 2024-03-05 10:24:57 INFO     1   HTTPApi Started.

2024-03-05T10:24:57.895Z | 2024-03-05 10:24:57 INFO     1   jCli Started.

2024-03-05T12:16:39.900Z | Unhandled Error

2024-03-05T12:16:39.900Z | Traceback (most recent call last):

2024-03-05T12:16:39.900Z |   File "/usr/local/lib/python3.8/site-packages/twisted/python/log.py", line 96, in callWithLogger

2024-03-05T12:16:39.900Z |     return callWithContext({"system": lp}, func, *args, **kw)

2024-03-05T12:16:39.900Z |   File "/usr/local/lib/python3.8/site-packages/twisted/python/log.py", line 80, in callWithContext

2024-03-05T12:16:39.900Z |     return context.call({ILogContext: newCtx}, func, *args, **kw)

2024-03-05T12:16:39.900Z |   File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 117, in callWithContext

2024-03-05T12:16:39.900Z |     return self.currentContext().callWithContext(ctx, func, *args, **kw)

2024-03-05T12:16:39.900Z |   File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 82, in callWithContext

2024-03-05T12:16:39.900Z |     return func(*args, **kw)

2024-03-05T12:16:39.900Z | --- <exception caught here> ---

2024-03-05T12:16:39.900Z |   File "/usr/local/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 683, in _doReadOrWrite

2024-03-05T12:16:39.900Z |     why = selectable.doRead()

2024-03-05T12:16:39.900Z |   File "/usr/local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 248, in doRead

2024-03-05T12:16:39.900Z |     return self._dataReceived(data)

2024-03-05T12:16:39.900Z |   File "/usr/local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 253, in _dataReceived

2024-03-05T12:16:39.900Z |     rval = self.protocol.dataReceived(data)

2024-03-05T12:16:39.900Z |   File "/usr/local/lib/python3.8/site-packages/twisted/conch/telnet.py", line 548, in dataReceived

2024-03-05T12:16:39.900Z |     raise ValueError("Stumped", b)

2024-03-05T12:16:39.900Z | builtins.ValueError: ('Stumped', b'\xec')

2024-03-05T12:16:39.900Z | 

2024-03-05T13:01:19.822Z | Unhandled Error

2024-03-05T13:01:19.822Z | Traceback (most recent call last):

2024-03-05T13:01:19.822Z |   File "/usr/local/lib/python3.8/site-packages/twisted/python/log.py", line 96, in callWithLogger

2024-03-05T13:01:19.822Z |     return callWithContext({"system": lp}, func, *args, **kw)

2024-03-05T13:01:19.822Z |   File "/usr/local/lib/python3.8/site-packages/twisted/python/log.py", line 80, in callWithContext

2024-03-05T13:01:19.822Z |     return context.call({ILogContext: newCtx}, func, *args, **kw)

2024-03-05T13:01:19.822Z |   File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 117, in callWithContext

2024-03-05T13:01:19.822Z |     return self.currentContext().callWithContext(ctx, func, *args, **kw)

2024-03-05T13:01:19.822Z |   File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 82, in callWithContext

2024-03-05T13:01:19.822Z |     return func(*args, **kw)

2024-03-05T13:01:19.822Z | --- <exception caught here> ---

2024-03-05T13:01:19.822Z |   File "/usr/local/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 683, in _doReadOrWrite

2024-03-05T13:01:19.822Z |     why = selectable.doRead()

2024-03-05T13:01:19.822Z |   File "/usr/local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 248, in doRead

2024-03-05T13:01:19.822Z |     return self._dataReceived(data)

2024-03-05T13:01:19.822Z |   File "/usr/local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 253, in _dataReceived

2024-03-05T13:01:19.822Z |     rval = self.protocol.dataReceived(data)

2024-03-05T13:01:19.822Z |   File "/usr/local/lib/python3.8/site-packages/twisted/conch/telnet.py", line 548, in dataReceived

2024-03-05T13:01:19.822Z |     raise ValueError("Stumped", b)

2024-03-05T13:01:19.822Z | builtins.ValueError: ('Stumped', b'\xec')

2024-03-05T13:01:19.822Z | 

2024-03-05T13:19:13.111Z | Unhandled Error

2024-03-05T13:19:13.111Z | Traceback (most recent call last):

2024-03-05T13:19:13.111Z |   File "/usr/local/lib/python3.8/site-packages/twisted/python/log.py", line 96, in callWithLogger

2024-03-05T13:19:13.111Z |     return callWithContext({"system": lp}, func, *args, **kw)

2024-03-05T13:19:13.111Z |   File "/usr/local/lib/python3.8/site-packages/twisted/python/log.py", line 80, in callWithContext

2024-03-05T13:19:13.111Z |     return context.call({ILogContext: newCtx}, func, *args, **kw)

2024-03-05T13:19:13.112Z |   File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 117, in callWithContext

2024-03-05T13:19:13.112Z |     return self.currentContext().callWithContext(ctx, func, *args, **kw)

2024-03-05T13:19:13.112Z |   File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 82, in callWithContext

2024-03-05T13:19:13.112Z |     return func(*args, **kw)

2024-03-05T13:19:13.112Z | --- <exception caught here> ---

2024-03-05T13:19:13.112Z |   File "/usr/local/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 683, in _doReadOrWrite

2024-03-05T13:19:13.112Z |     why = selectable.doRead()

2024-03-05T13:19:13.112Z |   File "/usr/local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 248, in doRead

2024-03-05T13:19:13.112Z |     return self._dataReceived(data)

2024-03-05T13:19:13.112Z |   File "/usr/local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 253, in _dataReceived

2024-03-05T13:19:13.112Z |     rval = self.protocol.dataReceived(data)

2024-03-05T13:19:13.112Z |   File "/usr/local/lib/python3.8/site-packages/twisted/conch/telnet.py", line 548, in dataReceived

2024-03-05T13:19:13.112Z |     raise ValueError("Stumped", b)

2024-03-05T13:19:13.112Z | builtins.ValueError: ('Stumped', b'\xec')

2024-03-05T13:19:13.112Z | 

2024-03-05T13:54:07.448Z | Unhandled Error

2024-03-05T13:54:07.448Z | Traceback (most recent call last):

2024-03-05T13:54:07.448Z |   File "/usr/local/lib/python3.8/site-packages/twisted/python/log.py", line 96, in callWithLogger

2024-03-05T13:54:07.448Z |     return callWithContext({"system": lp}, func, *args, **kw)

2024-03-05T13:54:07.448Z |   File "/usr/local/lib/python3.8/site-packages/twisted/python/log.py", line 80, in callWithContext

2024-03-05T13:54:07.448Z |     return context.call({ILogContext: newCtx}, func, *args, **kw)

2024-03-05T13:54:07.448Z |   File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 117, in callWithContext

2024-03-05T13:54:07.448Z |     return self.currentContext().callWithContext(ctx, func, *args, **kw)

2024-03-05T13:54:07.448Z |   File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 82, in callWithContext

2024-03-05T13:54:07.448Z |     return func(*args, **kw)

2024-03-05T13:54:07.448Z | --- <exception caught here> ---

2024-03-05T13:54:07.448Z |   File "/usr/local/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 683, in _doReadOrWrite

2024-03-05T13:54:07.448Z |     why = selectable.doRead()

2024-03-05T13:54:07.448Z |   File "/usr/local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 248, in doRead

2024-03-05T13:54:07.449Z |     return self._dataReceived(data)

2024-03-05T13:54:07.449Z |   File "/usr/local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 253, in _dataReceived

2024-03-05T13:54:07.449Z |     rval = self.protocol.dataReceived(data)

2024-03-05T13:54:07.449Z |   File "/usr/local/lib/python3.8/site-packages/twisted/conch/telnet.py", line 548, in dataReceived

2024-03-05T13:54:07.449Z |     raise ValueError("Stumped", b)

2024-03-05T13:54:07.449Z | builtins.ValueError: ('Stumped', b'\xec')

2024-03-05T13:54:07.449Z | 

2024-03-06T06:40:20.611Z | Unhandled Error

2024-03-06T06:40:20.611Z | Traceback (most recent call last):

**Comment by farirat** [comment]
What's the impact on jasmin ?

**Comment by bss-haresh-makwana** [comment]
Not Sure actual Impact of this error. We faced issue in Submit on Provider side(smppccm) & DLR passing back to user. Even we are not able reproduce same.
