### ISSUE TITLE
Command Length is invalid

### ISSUE THREAD

**Issue by hi-tech** [jookies/jasmin#124]
Getting an error binding to a new carrier (successful w/ simulator):

```
2015-03-16 15:45:21 WARNING  8546 Requesting bind as transceiver
2015-03-16 15:45:21 ERROR    8546 Command Length is invalid: Invalid command length: expected 17, parsed 16
Traceback (most recent call last):
  File "/opt/python2.7/lib/python2.7/site-packages/jasmin/vendor/smpp/twisted/protocol.py", line 195, in rawMessageReceived
    pdu = self.encoder.decode(StringIO.StringIO(message))
  File "/opt/python2.7/lib/python2.7/site-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 932, in decode
    raise PDUCorruptError("Invalid command length: expected %d, parsed %d" % (headerParams['command_length'], parsedLen), pdu_types.CommandStatus.ESME_RINVCMDLEN)
PDUCorruptError: Command Length is invalid: Invalid command length: expected 17, parsed 16
2015-03-16 15:45:21 CRITICAL 8546 Received corrupt PDU 0000001180000009000000530000000100
2015-03-16 15:45:21 CRITICAL 8546 Connection is corrupt!!! Shutting down...
```

kannel binds successfully.

Thanks.

**Comment by fourat** [comment]
Hi,

Can you please provide a tcp capture (pcap file) using tcpdump or wireshark where i can see the bind_transceiver_resp pdu ?

**Comment by hi-tech** [comment]
Hi, 

Apologies, you can close this issue. Simple config error as I was missing the **systype** field as per the invalid system_type error from the carrier as the dump indicates. Successfully binded once field added. Thanks for the tip on viewing the tcpdump.

```

===========================================================================================================================================
SM_PP Operations:
Topic / Item                Count         Average       Min val       Max val       Rate (ms)     Percent       Burst rate    Burst start  
-------------------------------------------------------------------------------------------------------------------------------------------
SMPP Operations             36                                                      0.0003        100%          0.0200        0.225        
 SMPP Responses             24                                                      0.0002        66.67%        0.0200        0.225        
  Generic_nack              12                                                      0.0001        50.00%        0.0100        0.226        
  Bind_transceiver - resp   12                                                      0.0001        50.00%        0.0100        0.225        
 SMPP Requests              12                                                      0.0001        33.33%        0.0100        0.000        
  Bind_transceiver          12                                                      0.0001        100.00%       0.0100        0.000        
SMPP Response Status        24                                                      0.0002        100%          0.0200        0.225        
 Invalid system_type field  12                                                      0.0001        50.00%        0.0100        0.225        
 Command length is invalid  12                                                      0.0001        50.00%        0.0100        0.226        

-------------------------------------------------------------------------------------------------------------------------------------------

```

**Comment by fourat** [comment]
Hi, anyway this must not lead to a **corrupted connection error**, can you please share the dump on fourat@gmail.com

**Comment by hi-tech** [comment]
Agreed, sanitized pcap sent. Thanks.
