### ISSUE TITLE
NULL terminated characters in the message field returns ESME_RINVMSGLEN

### ISSUE THREAD

**Issue by raamtg** [jookies/jasmin#218]
Hello,

The Jasmin SMS Server doesnt support NULL terminated characters in the message field of the SubmitSM PDU. Although the specs are not very clear on this item, it would be good to support it just in case some SMPP clients cannot turn off this.

See section 3.1 here:
http://www.activexperts.com/sms-component/smpp-specifications/pdu-type-format-definitions/ 

WITH null-terminated characters:

2015-06-17 15:52:50 WARNING  812 SMPP connection established from MYIPHERE to port 2775
2015-06-17 15:52:50 INFO     812 Added bind_transceiver bind for 'leighton'. Active binds: bind_receiver: 0, bind_transceiver: 1, bind_transmitter: 0.
2015-06-17 15:52:50 INFO     812 Bind request succeeded for leighton in session [aa437fab-aa77-41ed-8c90-684d1e9ff019]. 1 active binds
2015-06-17 15:52:50 ERROR    812 Message Length is invalid: Length mismatch. Expecting 2 bytes. Read 1
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/jasmin/vendor/smpp/twisted/protocol.py", line 195, in rawMessageReceived
    pdu = self.encoder.decode(StringIO.StringIO(message))
  File "/usr/lib/python2.7/site-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 930, in decode
    def decode(self, file):
  File "/usr/lib/python2.7/site-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 970, in decodeBody
    if len(pdu.mandatoryParams) > 0:
  File "/usr/lib/python2.7/site-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1017, in decodeOptionalParams
    
  File "/usr/lib/python2.7/site-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 821, in decode
    Int2Encoder().encode(length),
  File "/usr/lib/python2.7/site-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 88, in decode
    bytes = self._read(file)
  File "/usr/lib/python2.7/site-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 259, in _read
    return self.encoder._read(file)
  File "/usr/lib/python2.7/site-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 152, in _read
    return self.read(file, self.size)
  File "/usr/lib/python2.7/site-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 45, in read
    raise PDUCorruptError("Length mismatch. Expecting %d bytes. Read %d" % (size, length), pdu_types.CommandStatus.ESME_RINVMSGLEN)
PDUCorruptError: Message Length is invalid: Length mismatch. Expecting 2 bytes. Read 1
2015-06-17 15:52:50 CRITICAL 812 Received corrupt PDU 00000077000000040000000000000002000500534d505054657374657200010131323334353636370000000000000100000043546869732069732061207465737420534d5050206d6573736167652073656e742066726f6d20206f6e20323031352d30362d31372061742031343a35323a3530706d2e00
2015-06-17 15:52:50 CRITICAL 812 Connection is corrupt!!! Shutting down...
2015-06-17 15:52:50 WARNING  812 Shutdown requested...disconnecting
2015-06-17 15:52:50 WARNING  812 Disconnecting while bound to SMSC...
2015-06-17 15:52:50 INFO     812 Dropped bind_transceiver bind for 'leighton'. Active binds: bind_receiver: 0, bind_transceiver: 0, bind_transmitter: 0.
2015-06-17 15:52:50 WARNING  812 SMPP MYIPHERE disconnected from port 2775: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]

WITHOUT null-terminated characters:
2015-06-17 15:56:23 WARNING  812 SMPP connection established from MYIPHERE to port 2775
2015-06-17 15:56:23 INFO     812 Added bind_transceiver bind for 'leighton'. Active binds: bind_receiver: 0, bind_transceiver: 1, bind_transmitter: 0.
2015-06-17 15:56:23 INFO     812 Bind request succeeded for leighton in session [64a05144-a984-4606-bf88-1c11ee32c729]. 1 active binds
2015-06-17 15:56:23 WARNING  812 Disconnecting...
2015-06-17 15:56:23 INFO     812 Dropped bind_transceiver bind for 'leighton'. Active binds: bind_receiver: 0, bind_transceiver: 0, bind_transmitter: 0.
2015-06-17 15:56:23 WARNING  812 SMPP MYIPHERE disconnected from port 2775: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.

Refer to https://groups.google.com/forum/#!topic/jasmin-sms-gateway/f5Zixeux8rw for the pcaps. There are two pcaps:

One from my server that consists of both an SMPP client and a server – I have done two requests here (one with null-terminated - packet 20, and one without – packet 44). Both requests were responded to successfully although Wireshark seems to think the former is malformed.

The second pcap is run on the Jasmin server for all requests on port 2775 (packets 8 and 22). In this case, only the one without the null-terminated characters was successful

**Comment by zoufou** [comment]
Hi @raamtg 
I've inspected your provided pcaps and can confirm that there's no issue at Jasmin side (wireshark is correct as well), here's my explanation:

Based on packet n°20 in the atatched pcap file, the submit_sm pdu is **really** malformed:

* Look at byte n°118 (0x78), it indicate the message length: 66 bytes
* Message content has 67 bytes (including the null 0x00 byte), and that's the error !

[RaamSMPP-Port9998.pcap](https://files.zenhub.io/5675cfe444a39b9770d636b2)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
