### ISSUE TITLE
Error in the optional part of the PDU Body: Unknown tag value 0x60d

### ISSUE THREAD

**Issue by zoufou** [jookies/jasmin#325]
It may be related to #322 as well

    ERROR 318 Error in the optional part of the PDU Body: Unknown tag value 0x60d

    Traceback (most recent call last):

    File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/twisted/protocol.py", line 195, in rawMessageReceived

    pdu = self.encoder.decode(StringIO.StringIO(message))

    File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 945, in decode

    self.decodeBody(file, pdu, headerParams['command_length'] - self.HEADER_LEN)

    File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 985, in decodeBody

    optionalParams = self.decodeOptionalParams(pdu.optionalParams, file, bodyLength - mParamsLen)

    File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1032, in decodeOptionalParams

    option = self.optionEncoder.decode(file)

    File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 836, in decode

    tag = TagEncoder().decode(file)

    File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 96, in decode

    return self._decode(bytes)

    File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 271, in _decode

    raise self.decodeErrorClass(errStr, self.decodeErrorStatus)

    PDUParseError: Error in the optional part of the PDU Body: Unknown tag value 0x60d

    2015-10-09 01:05:07 CRITICAL 318 Received unparsable PDU 000000de0000000500000000569d3e3600000033353236393136303034303300000030000400000000000000008569643a3444313943383343207375623a30303120646c7672643a303031207375626d697420646174653a3135313030393031303520646f6e6520646174653a3135313030393031303520737461743a44454c49565244206572723a3030303020746578743a4757323530204d43433d323730204d4e433d312042696c6c696e674d4e433d31001e0009344431394338334300000e000101060d000731323730303100060f000532373030310427000102

**Comment by zoufou** [comment]
As reported by some user:

    2015-11-10 07:53:51 CRITICAL 21743 Rejecting SubmitSmPDU[3e48a475-0502-4728-a0e2 -3b0114f62eec] through [cid:******] for an unknown error (<type 'exceptions.Va lueError'>): Value (38636) size 5 does not match expected 1

The issue is still open, seems to be size encoding of vendor tags.
