### ISSUE TITLE
CRITICAL 560 Received unparsable PDU

### ISSUE THREAD

**Issue by tewodrosa** [jookies/jasmin#399]
Hi All,

I get the following error when i receive incoming (MO) SMS. Please see log output below:

`2016-02-29 17:58:48 ERROR    560 Optional Parameter not allowed: Invalid option sc_interface_version
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/twisted/protocol.py", line 195, in rawMessageReceived
    pdu = self.encoder.decode(StringIO.StringIO(message))
  File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 961, in decode
    self.decodeBody(file, pdu, headerParams['command_length'] - self.HEADER_LEN)
  File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1001, in decodeBody
    optionalParams = self.decodeOptionalParams(pdu.optionalParams, file, bodyLength - mParamsLen)
  File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1051, in decodeOptionalParams
    raise PDUParseError("Invalid option %s" % optionName, pdu_types.CommandStatus.ESME_ROPTPARNOTALLWD)
PDUParseError: Optional Parameter not allowed: Invalid option sc_interface_version
2016-02-29 17:58:48 CRITICAL 560 Received unparsable PDU 000000420000000500000000000000fa5741500001013236383736303630323932000001333833380000000000000000000004546573740204000200c50210000134`

**Comment by farirat** [comment]
The error is self-explaining, the sc_interface_version is not supported within deliver_sm pdu, you can still add it into the pdu decoder if you are easy with python.

**Comment by tewodrosa** [comment]
Hi, I am not that well versed with python, any pointer or guidance will be much appreciated.

**Comment by tewodrosa** [comment]
Anyone?

**Comment by farirat** [comment]
Closing issue for inactivity
