### ISSUE TITLE
ImportError: No module named web 

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#412]
Hi I was not able to start jasmin from normal installation. After running it directly i am getting the below error about  missing web module. 

please advice. 

root@chd-ltsp1:/home/anshu/jasmin# jasmind.py --username jcliadmin --password jclipwd
Traceback (most recent call last):
  File "/usr/local/bin/jasmind.py", line 4, in <module>
    __import__('pkg_resources').run_script('jasmin==0.9b2', 'jasmind.py')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1490, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/jasmin-0.9b2-py2.7.egg/EGG-INFO/scripts/jasmind.py", line 11, in <module>
    
ImportError: No module named web

**Comment by sah-anshu** [comment]
Platform : Ubuntu 14.04.3 LTS /Python 2.7.6 /pip 8.1.1

**Comment by farirat** [comment]
From the docs the deb packaging is only available for 15.04 and higher, you should use pypi installation instead on any other platform.
