### ISSUE TITLE
SMPPClientConfig added via PB will crash server when queried via jcli

### ISSUE THREAD

**Issue by aivisol** [jookies/jasmin#544]
How to reproduce:

Use example using_pb.py script to add SMPPClientConfig.

Then login via jcli and issue:
`smppccm -s abc`

You will get:
`Connection closed by foreign host.`

And server traceback:

`Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/local/lib/python2.7/dist-packages/twisted/conch/telnet.py", line 636, in dataReceived
    self.applicationDataReceived(b''.join(appDataBuffer))
  File "/usr/local/lib/python2.7/dist-packages/twisted/conch/telnet.py", line 988, in applicationDataReceived
    self.protocol.dataReceived(data)
  File "/usr/local/lib/python2.7/dist-packages/twisted/conch/telnet.py", line 1035, in dataReceived
    self.protocol.dataReceived(data)
  File "/usr/local/lib/python2.7/dist-packages/twisted/conch/insults/insults.py", line 537, in dataReceived
    self.terminalProtocol.keystrokeReceived(ch, None)
  File "/usr/local/lib/python2.7/dist-packages/twisted/conch/recvline.py", line 225, in keystrokeReceived
    m()
  File "/usr/local/lib/python2.7/dist-packages/twisted/conch/recvline.py", line 374, in handle_RETURN
    return RecvLine.handle_RETURN(self)
  File "/usr/local/lib/python2.7/dist-packages/twisted/conch/recvline.py", line 292, in handle_RETURN
    self.lineReceived(line)
  File "/usr/lib/python2.7/dist-packages/jasmin/protocols/cli/jcli.py", line 86, in lineReceived
    return CmdProtocol.lineReceived(self, line)
  File "/usr/lib/python2.7/dist-packages/jasmin/protocols/cli/protocol.py", line 157, in lineReceived
    return func(arg)
  File "/usr/lib/python2.7/dist-packages/jasmin/protocols/cli/options.py", line 81, in new_func
    return func(instance, arg, opts)
  File "/usr/lib/python2.7/dist-packages/jasmin/protocols/cli/jcli.py", line 393, in do_smppccm
    self.managers['smppccm'].show(arg, opts)
  File "/usr/lib/python2.7/dist-packages/jasmin/protocols/cli/smppccm.py", line 198, in exist_connector_and_call
    return fCallback(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/jasmin/protocols/cli/smppccm.py", line 326, in show
    for k, v in connector['config'].getAll().iteritems():
exceptions.AttributeError: 'SMPPClientConfig' object has no attribute 'getAll'

`

**Comment by farirat** [comment]
Unreproducible error (0.9.25+ and 0.10.1+)
