### ISSUE TITLE
Optional Parameter not allowed: Invalid option more_messages_to_send

### ISSUE THREAD

**Issue by sideeq** [jookies/jasmin#545]
Dears, 

I'm trying to setup a smppccm and i receive this error and the messages never go throw out jasmin server, can you please help me ? 

```
2017-03-09 11:57:25 INFO     19274 Establishing TCP connection to XXXXXXXXX:XXXX
2017-03-09 11:57:25 INFO     19274 Connecting to IPv4Address(TCP, 'XXXXXXXX', XXXXX) ...
2017-03-09 11:57:25 WARNING  19274 SMPP connection established from XXXXXXX to port XXXX
2017-03-09 11:57:25 INFO     19274 Connection made to XXXXXXX:XXXXXXX
2017-03-09 11:57:25 WARNING  19274 Requesting bind as transceiver
2017-03-09 11:57:25 WARNING  19274 Bind succeeded...now in state BOUND_TRX
2017-03-09 11:59:31 ERROR    19274 Optional Parameter not allowed: Invalid option more_messages_to_send
```

**Comment by kissonde** [comment]
Have you overcome this problem? If so, how? We're facing this as we speak.

**Comment by farirat** [comment]
Where are you getting this error ? for deliver or submit ?

**Comment by kissonde** [comment]
For deliver

**Comment by kissonde** [comment]
2018-11-29 17:07:52 ERROR    1 Optional Parameter not allowed: Invalid option more_messages_to_send
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/twisted/protocol.py", line 195, in rawMessageReceived
    pdu = self.encoder.decode(StringIO.StringIO(message))
  File "/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 965, in decode
    self.decodeBody(file, pdu, headerParams['command_length'] - self.HEADER_LEN)
  File "/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1005, in decodeBody
    optionalParams = self.decodeOptionalParams(pdu.optionalParams, file, bodyLength - mParamsLen)
  File "/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1060, in decodeOptionalParams
    raise PDUParseError("Invalid option %s" % optionName, pdu_types.CommandStatus.ESME_ROPTPARNOTALLWD)
PDUParseError: Optional Parameter not allowed: Invalid option more_messages_to_send

**Comment by kissonde** [comment]
Parsing TLV: 4, 38, 0, 1, 0

**Comment by farirat** [comment]
I guess this is not supported for deliver_sm pdus, you still can file a feature request for next releases.
