### ISSUE TITLE
MO - Invalid Optional Parameter Value: Unknown callback_num_digit_mode_indicator value

### ISSUE THREAD

**Issue by gsmbillingpl** [jookies/jasmin#549]
I have a setup of SMPP connectors the ones for MT are fine but when I test  MO i get this 👍 

`2017-03-16 14:26:13 ERROR    878 Invalid Optional Parameter Value: Unknown callback_num_digit_mode_indicator value 0x71
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/twisted/protocol.py", line 195, in rawMessageReceived
    pdu = self.encoder.decode(StringIO.StringIO(message))
  File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 965, in decode
    self.decodeBody(file, pdu, headerParams['command_length'] - self.HEADER_LEN)
  File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1005, in decodeBody
    optionalParams = self.decodeOptionalParams(pdu.optionalParams, file, bodyLength - mParamsLen)
  File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1057, in decodeOptionalParams
    option = self.optionEncoder.decode(file)
  File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 867, in decode
    raise e
PDUParseError: Invalid Optional Parameter Value: Unknown callback_num_digit_mode_indicator value 0x71
2017-03-16 14:26:13 CRITICAL 878 Received unparsable PDU 0000005500000005000000000000003100010134383533313833313538340001013438373939333532323232000000000000000000000857726f636c617720038100077130410282844002020007a032363
^C
`

Specification give by the carrier:
1x SMPP 3.4 Receiver
through output 100

MO is relayed to your platform using the deliver_sm operation. For details on the deliver_sm operation and the PDU, please refer to the SMPP 3.4 documentation.
After you receive a deliver_sm, you need to acknowldege the receipt by answering with a deliver_sm_resp. Otherwise, we will resend the deliver_sm.

> Features
Timestamp - Shows the actual time when the mobile subscriber sent the SMS.
Global Title of sending SMSC - Identifies the sending SMSC by its MCC/MNC.
TON/NPI - passes through the TON/NPI values of the originator.

I would really appreciate some insight in this error please.

**Comment by SteveAyre** [comment]
Is that the entire PDU? If so it's invalid. There's a callback_num TLV followed by a source_subaddress TLV with a 7 byte length and less data than that. Looks like you might have cut it mid-octet though so I suspect it not the entire PDU. Can you post the full PDU?

**Comment by gsmbillingpl** [comment]
Thank you for your reply and I am sorry it was fault on  our side. Carrier was sending additional parameters. After switching them off all is working fine.
