### ISSUE TITLE
Long Unicode SMS receiving in 2 parts

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#552]
Hi

I am receiving Long Unicode SMS in 2 Parts .Have anyone experienced it ? Our Its just due to any configuration?

Downlink is Kannel ->> JASMIN -->> Uplink 

-
Anshu

**Comment by farirat** [comment]
Which release ? MO or MT ? can you share a pcap ?

**Comment by sah-anshu** [comment]
I will try to regenerate the error. till then i have some traces. 



2017-04-03 12:51:54 ERROR    1537 Unknown Error: Unknown command_status 34
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/jasmin/vendor/smpp/twisted/protocol.py", line 195, in rawMessageReceived
    pdu = self.encoder.decode(StringIO.StringIO(message))
  File "build/bdist.linux-x86_64/egg/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 962, in decode
    headerParams = self.decodeHeader(file)
  File "build/bdist.linux-x86_64/egg/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 982, in decodeHeader
    headerParams = self.decodeRequiredParams(self.HeaderParams, self.HeaderEncoders, file)
  File "build/bdist.linux-x86_64/egg/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1070, in decodeRequiredParams
   params[paramName] = encoderMap[paramName].decode(file)
  File "build/bdist.linux-x86_64/egg/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 96, in decode
    return self._decode(bytes)
  File "build/bdist.linux-x86_64/egg/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 330, in _decode
    raise PDUParseError("Unknown command_status %s" % intval, pdu_types.CommandStatus.ESME_RUNKNOWNERR)
PDUParseError: Unknown Error: Unknown command_status 34
2017-04-03 12:51:54 CRITICAL 1537 Received unparsable PDU 00000010800000040000002200000008
2017-04-03 12:51:54 WARNING  1537 SMPP 180.179.146.72 disconnected from port 33730: [Failure instance: Traceback (failure with no frames): <type 'exceptions.TypeError'>: 'NoneType' object is not callable
]
2017-04-03 12:51:54 ERROR    1537 Connection lost. Reason: [Failure instance: Traceback (failure with no frames): <type 'exceptions.TypeError'>: 'NoneType' object is not callable
