### ISSUE TITLE
Unknown Error: Unknown command_status 34 

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#563]
2017-04-27 10:29:56 WARNING  438 Requesting bind as transceiver
2017-04-27 10:29:57 WARNING  438 Bind succeeded...now in state BOUND_TRX
2017-04-27 10:29:59 ERROR    438 Unknown Error: Unknown command_status 34
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/jasmin/vendor/smpp/twisted/protocol.py", line 195, in rawMessageReceived
    pdu = self.encoder.decode(StringIO.StringIO(message))
  File "build/bdist.linux-x86_64/egg/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 962, in decode
    headerParams = self.decodeHeader(file)
  File "build/bdist.linux-x86_64/egg/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 982, in decodeHeader
    headerParams = self.decodeRequiredParams(self.HeaderParams, self.HeaderEncoders, file)
  File "build/bdist.linux-x86_64/egg/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1070, in decodeRequiredParams
    params[paramName] = encoderMap[paramName].decode(file)
  File "build/bdist.linux-x86_64/egg/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 96, in decode
    return self._decode(bytes)
  File "build/bdist.linux-x86_64/egg/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 330, in _decode
    raise PDUParseError("Unknown command_status %s" % intval, pdu_types.CommandStatus.ESME_RUNKNOWNERR)
PDUParseError: Unknown Error: Unknown command_status 34
2017-04-27 10:29:59 CRITICAL 438 Received unparsable PDU 00000010800000040000002200000002

- Repeatedly i am getting this error from my uplink. Can you let me know what could be solution to this. 

Regds
Anshu

**Comment by sah-anshu** [comment]
this was vendor specific submit_sm response. I commented code for now which was raising this error. 
We should show some tolerance for vendor specific command_status. If we don't find command_status in list we should not raise error.

My Vendor added these command status:
Value (Hex/Dec) Description 
0x00000022 / 34 Network not covered 
0x000000FF / 255 Account has insufficient balance 
0x0000000a Invalid_Source_Address 
0x0000000c Duplicate_Message_ID 
0x000004a1 System_Error or Account_Disabled 
0x0000000b Invalid Destination Address

**Comment by sah-anshu** [comment]
- Fixed.
