### ISSUE TITLE
Problems connecting to provider

### ISSUE THREAD

**Issue by Philio** [jookies/jasmin#577]
We're trying to setup Jasmin to connect to a new provider but are having trouble getting the SMPP connection to work.

Here is the output from the log:

    2017-05-16 11:22:39 INFO     28978 Establishing TCP connection to -----:9020
    2017-05-16 11:22:39 INFO     28978 Connecting to IPv4Address(TCP, '-----', 9020) ...
    2017-05-16 11:22:39 WARNING  28978 SMPP connection established from ----- to port 48500
    2017-05-16 11:22:39 INFO     28978 Connection made to -----:9020
    2017-05-16 11:22:39 WARNING  28978 Requesting bind as transceiver
    2017-05-16 11:22:41 ERROR    28978 Optional Parameter not allowed: Invalid option vendor_specific_bypass
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/twisted/protocol.py", line 195, in rawMessageReceived
    pdu = self.encoder.decode(StringIO.StringIO(message))
      File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 969, in decode
    self.decodeBody(file, pdu, headerParams['command_length'] - self.HEADER_LEN)
      File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1009, in decodeBody
    optionalParams = self.decodeOptionalParams(pdu.optionalParams, file, bodyLength - mParamsLen)
      File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1064, in decodeOptionalParams
    raise PDUParseError("Invalid option %s" % optionName, pdu_types.CommandStatus.ESME_ROPTPARNOTALLWD)
    PDUParseError: Optional Parameter not allowed: Invalid option vendor_specific_bypass
    2017-05-16 11:22:41 CRITICAL 28978 Received unparsable PDU 0000001c80000009000000000000000159656e746131001002000134
    2017-05-16 11:22:41 WARNING  28978 SMPP ----- disconnected from port 48500: [Failure instance: Traceback (failure with no frames): <type 'exceptions.AttributeError'>: type object 'BindTransceiverResp' has no attribute 'requireAck']
    2017-05-16 11:22:41 ERROR    28978 Connection lost. Reason: [Failure instance: Traceback (failure with no frames): <type 'exceptions.AttributeError'>: type object 'BindTransceiverResp' has no attribute 'requireAck'

Any settings we can change to try and resolve this?

**Comment by farirat** [comment]
Hey @Philio,

Can you tell if this pdu is received from another Jasmin node or a third party smpp server ?

Do you have a tcp dump where i can see the pdu ?

**Comment by Philio** [comment]
Hi @farirat 

Here is a TCP dump of some of the packets:

    # tcpdump -nnvvXSs 1514 -i eth0 "tcp[tcpflags] & (tcp-syn) != 0"
    tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 1514 bytes
    23:15:42.139188 IP (tos 0x0, ttl 64, id 41658, offset 0, flags [DF], proto TCP (6), length 60)
        139.*.*.*.48592 > 54.*.*.8.9020: Flags [S], cksum 0x9bb7 (incorrect -> 0x4590), seq 1190376182, win 29200, options [mss 1460,sackOK,TS val 160698444 ecr 0,nop,wscale 7], length 0
	    0x0000:  4500 003c a2ba 4000 4006 fc78 8ba2 fdfd  E..<..@.@..x....
	    0x0010:  36e4 db04 bdd0 233c 46f3 b2f6 0000 0000  6.....#<F.......
	    0x0020:  a002 7210 9bb7 0000 0204 05b4 0402 080a  ..r.............
	    0x0030:  0994 104c 0000 0000 0103 0307            ...L........
    23:15:42.150974 IP (tos 0x0, ttl 116, id 7621, offset 0, flags [DF], proto TCP (6), length 60)
        54.*.*.*.9020 > 139.*.*.*.48592: Flags [S.], cksum 0xb8f7 (correct), seq 981577668, ack 1190376183, win 8192, options [mss 1460,nop,wscale 8,sackOK,TS val 1532926194 ecr 160698444], length 0
	    0x0000:  4500 003c 1dc5 4000 7406 4d6e 36e4 db04  E..<..@.t.Mn6...
	    0x0010:  8ba2 fdfd 233c bdd0 3a81 afc4 46f3 b2f7  ....#<..:...F...
	    0x0020:  a012 2000 b8f7 0000 0204 05b4 0103 0308  ................
	    0x0030:  0402 080a 5b5e 98f2 0994 104c            ....[^.....L
    23:15:54.179002 IP (tos 0x0, ttl 64, id 9037, offset 0, flags [DF], proto TCP (6), length 60)
        139.*.*.*.48594 > 54.*.*.*.9020: Flags [S], cksum 0x9bb7 (incorrect -> 0x3600), seq 3191225637, win 29200, options [mss 1460,sackOK,TS val 160702056 ecr 0,nop,wscale 7], length 0
	    0x0000:  4500 003c 234d 4000 4006 7be6 8ba2 fdfd  E..<#M@.@.{.....
	    0x0010:  36e4 db04 bdd2 233c be36 3d25 0000 0000  6.....#<.6=%....
	    0x0020:  a002 7210 9bb7 0000 0204 05b4 0402 080a  ..r.............
	    0x0030:  0994 1e68 0000 0000 0103 0307            ...h........
    23:15:54.190632 IP (tos 0x0, ttl 116, id 8646, offset 0, flags [DF], proto TCP (6), length 60)
        54.*.*.*.9020 > 139.*.*.*.48594: Flags [S.], cksum 0xc937 (correct), seq 2767200465, ack 3191225638, win 8192, options [mss 1460,nop,wscale 8,sackOK,TS val 1532927398 ecr 160702056], length 0
	    0x0000:  4500 003c 21c6 4000 7406 496d 36e4 db04  E..<!.@.t.Im6...
	    0x0010:  8ba2 fdfd 233c bdd2 a4f0 20d1 be36 3d26  ....#<.......6=&
	    0x0020:  a012 2000 c937 0000 0204 05b4 0103 0308  .....7..........
	    0x0030:  0402 080a 5b5e 9da6 0994 1e68            ....[^.....h

I noticed you offer commercial support too, we'd be interested to find out more about this if you think this might be something you can resolve for us.

**Comment by farirat** [comment]
Hey @Philio, for sure, please file your issue to support@jasminsms.com

We'll sort it out quickly, by the way i want the gh-577.pcap from this command:

`tcpdump -s0 -i eth0 -w /tmp/gh-577.pcap`

Let it run for some time till you catch the issue in jasmin's log, then ctrl+c and send me back the pcap file to support@jasminsms.com

**Comment by Philio** [comment]
Thanks @farirat - I've emailed you.

**Comment by farirat** [comment]
@Philio  your issue were addressed today and resolved in v0.9rc23 actually.

The build process may take some time to pass, it's publicly available here: https://travis-ci.org/jookies/jasmin

There's a bunch of builds to run to ensure all tests are okay between every branch merge, plus the packaging for debian, redhat, pypi and docker, so please expect it to be available end of this day.

I've also notified you through the customer support portal.
