### ISSUE TITLE
twisted.spread.banana.BananaError: Security precaution: more than 64 bytes of prefix

### ISSUE THREAD

**Issue by sah-anshu** [jookies/jasmin#660]
HI, I wonder what could have raised this:

Mar 14 07:03:50 localhost jasmind[740]: --- <exception caught here> ---
Mar 14 07:03:50 localhost jasmind[740]:   File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrW
Mar 14 07:03:50 localhost jasmind[740]:     why = selectable.doRead()
Mar 14 07:03:50 localhost jasmind[740]:   File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 205, in doRead
Mar 14 07:03:50 localhost jasmind[740]:     return self._dataReceived(data)
Mar 14 07:03:50 localhost jasmind[740]:   File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 211, in _dataReceived
Mar 14 07:03:50 localhost jasmind[740]:     rval = self.protocol.dataReceived(data)
Mar 14 07:03:50 localhost jasmind[740]:   File "/usr/local/lib/python2.7/dist-packages/twisted/spread/banana.py", line 191, in dataReceived
Mar 14 07:03:50 localhost jasmind[740]:     raise BananaError("Security precaution: more than %d bytes of prefix" % (self.prefixLimit,))
Mar 14 07:03:50 localhost jasmind[740]: twisted.spread.banana.BananaError: Security precaution: more than 64 bytes of prefix

**Comment by farirat** [comment]
Any data to reproduce the issue ? is it 0.9.27 ?

**Comment by devrajatverma** [comment]
also facing the same when bitbucket web hook is received
`2018-07-06 15:31:45+0530 [Broker,2,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rajat/anaconda3/envs/buildbot/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rajat/anaconda3/envs/buildbot/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rajat/anaconda3/envs/buildbot/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rajat/anaconda3/envs/buildbot/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rajat/anaconda3/envs/buildbot/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rajat/anaconda3/envs/buildbot/lib/python3.6/site-packages/twisted/internet/tcp.py", line 205, in doRead
	    return self._dataReceived(data)
	  File "/home/rajat/anaconda3/envs/buildbot/lib/python3.6/site-packages/twisted/internet/tcp.py", line 211, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rajat/anaconda3/envs/buildbot/lib/python3.6/site-packages/twisted/spread/banana.py", line 191, in dataReceived
	    raise BananaError("Security precaution: more than %d bytes of prefix" % (self.prefixLimit,))
	twisted.spread.banana.BananaError: Security precaution: more than 64 bytes of prefix
`
