### ISSUE TITLE
SMPP client got disconnected after dlr sent!

### ISSUE THREAD

**Issue by nullimit** [jookies/jasmin#681]
Hi,

I'm having problem with the jasmin deliversm response, whenever jasmin sent out the delivery report to users, its got disconnected with log as follow:

2018-05-30 13:43:47 INFO     1644 SMS-MT [uid:c-smpp] [cid:j-smpp] [msgid:c5c2cbc6-cfd6-4598-afbd-436ec5f179d1] [prio:0] [from:abcd] [to:658128389] [content:test sms 123]
2018-05-30 13:43:52 INFO     1644 DELIVER_SM [uid:c-smpp] [from:658128389] [to:abcd] [content: id:c5c2cbc6-cfd6-4598-afbd-436ec5f179d1 submit date:201805301343 done date:201805301343 stat:DELIVRD err:002]
2018-05-30 13:43:52 ERROR    1644 Unknown Error: Field must be null
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/twisted/protocol.py", line 195, in rawMessageReceived
    pdu = self.encoder.decode(StringIO.StringIO(message))
  File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1023, in decode
    self.decodeBody(file, pdu, headerParams['command_length'] - self.HEADER_LEN)
  File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1065, in decodeBody
    mandatoryParams = self.decodeRequiredParams(pdu.mandatoryParams, self.getRequiredParamEncoders(pdu), file)
  File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1174, in decodeRequiredParams
    params[paramName] = encoderMap[paramName].decode(file)
  File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 99, in decode
    raise PDUParseError("Field must be null", pdu_types.CommandStatus.ESME_RUNKNOWNERR)
PDUParseError: Unknown Error: Field must be null
2018-05-30 13:43:52 CRITICAL 1644 Received unparsable PDU 0000001f8000000500000000000000013133343234382d35303430302d3200
2018-05-30 13:43:52 INFO     1644 Dropped bind_transceiver bind for 'c-smpp'. Active binds: bind_receiver: 0, bind_transceiver: 0, bind_transmitter: 0.
2018-05-30 13:43:52 WARNING  1644 SMPP 100.102.50.10 disconnected from port 2750: [Failure instance: Traceback (failure with no frames): <type 'exceptions.AttributeError'>: type object 'DeliverSMResp' has no attribute 'requireAck']

I checked that the smpp clients(c-smpp) sent out some deliversm response with log as follow:

[SMPPClient(j-smpp)] abcd->658128389(id:c5c2cbc6-cfd6-4598-afbd-436ec5f179d1) -- DELIVERSM RESPONSE >> status:0x00000000

Can kindly advise on how to handle the deliversm response from the clients? or advise how to solve the disconnection problems?

Thanks in advance,
Nullimit

**Comment by farirat** [comment]
Please make a tcp capture file and share it.
