### ISSUE TITLE
KeyError exception in systemd journal

### ISSUE THREAD

**Issue by terrycain** [jookies/jasmin#684]
On a few of my SMPP servers I see this every now and again.

```
May 16 10:33:16 smpp-prod3 jasmind[13382]: Unhandled error in Deferred:
May 24 10:30:03 smpp-prod3 jasmind[13382]: Unhandled error in Deferred:
May 24 10:30:03 smpp-prod3 jasmind[13382]: Unhandled Error
May 24 10:30:03 smpp-prod3 jasmind[13382]: Traceback (most recent call last):
May 24 10:30:03 smpp-prod3 jasmind[13382]: File "/usr/bin/jasmind.py", line 534, in <module>
May 24 10:30:03 smpp-prod3 jasmind[13382]: reactor.run()
May 24 10:30:03 smpp-prod3 jasmind[13382]: File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
May 24 10:30:03 smpp-prod3 jasmind[13382]: self.mainLoop()
May 24 10:30:03 smpp-prod3 jasmind[13382]: File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1252, in mainLoop
May 24 10:30:03 smpp-prod3 jasmind[13382]: self.runUntilCurrent()
May 24 10:30:03 smpp-prod3 jasmind[13382]: --- <exception caught here> ---
May 24 10:30:03 smpp-prod3 jasmind[13382]: File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
May 24 10:30:03 smpp-prod3 jasmind[13382]: call.func(*call.args, **call.kw)
May 24 10:30:03 smpp-prod3 jasmind[13382]: File "/usr/lib/python2.7/site-packages/jasmin/vendor/smpp/twisted/protocol.py", line 507, in onResponseTimeout
May 24 10:30:03 smpp-prod3 jasmind[13382]: self.endOutboundTransactionErr(reqPDU, SMPPRequestTimoutError(errMsg))
May 24 10:30:03 smpp-prod3 jasmind[13382]: File "/usr/lib/python2.7/site-packages/jasmin/vendor/smpp/twisted/protocol.py", line 497, in endOutboundTransactionErr
May 24 10:30:03 smpp-prod3 jasmind[13382]: txn = self.closeOutboundTransaction(reqPDU.seqNum)
May 24 10:30:03 smpp-prod3 jasmind[13382]: File "/usr/lib/python2.7/site-packages/jasmin/vendor/smpp/twisted/protocol.py", line 469, in closeOutboundTransaction
May 24 10:30:03 smpp-prod3 jasmind[13382]: txn = self.outTxns[seqNum]
May 24 10:30:03 smpp-prod3 jasmind[13382]: exceptions.KeyError: 6
May 24 10:30:03 smpp-prod3 jasmind[13382]: Unhandled error in Deferred:
May 24 11:02:37 smpp-prod3 jasmind[13382]: Unhandled error in Deferred:
May 24 11:02:37 smpp-prod3 jasmind[13382]: Unhandled Error
May 24 11:02:37 smpp-prod3 jasmind[13382]: Traceback (most recent call last):
May 24 11:02:37 smpp-prod3 jasmind[13382]: File "/usr/bin/jasmind.py", line 534, in <module>
May 24 11:02:37 smpp-prod3 jasmind[13382]: reactor.run()
May 24 11:02:37 smpp-prod3 jasmind[13382]: File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
May 24 11:02:37 smpp-prod3 jasmind[13382]: self.mainLoop()
May 24 11:02:37 smpp-prod3 jasmind[13382]: File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1252, in mainLoop
May 24 11:02:37 smpp-prod3 jasmind[13382]: self.runUntilCurrent()
May 24 11:02:37 smpp-prod3 jasmind[13382]: --- <exception caught here> ---
May 24 11:02:37 smpp-prod3 jasmind[13382]: File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
May 24 11:02:37 smpp-prod3 jasmind[13382]: call.func(*call.args, **call.kw)
May 24 11:02:37 smpp-prod3 jasmind[13382]: File "/usr/lib/python2.7/site-packages/jasmin/vendor/smpp/twisted/protocol.py", line 507, in onResponseTimeout
May 24 11:02:37 smpp-prod3 jasmind[13382]: self.endOutboundTransactionErr(reqPDU, SMPPRequestTimoutError(errMsg))
May 24 11:02:37 smpp-prod3 jasmind[13382]: File "/usr/lib/python2.7/site-packages/jasmin/vendor/smpp/twisted/protocol.py", line 497, in endOutboundTransactionErr
May 24 11:02:37 smpp-prod3 jasmind[13382]: txn = self.closeOutboundTransaction(reqPDU.seqNum)
May 24 11:02:37 smpp-prod3 jasmind[13382]: File "/usr/lib/python2.7/site-packages/jasmin/vendor/smpp/twisted/protocol.py", line 469, in closeOutboundTransaction
May 24 11:02:37 smpp-prod3 jasmind[13382]: txn = self.outTxns[seqNum]
May 24 11:02:37 smpp-prod3 jasmind[13382]: exceptions.KeyError: 2
May 24 11:02:37 smpp-prod3 jasmind[13382]: Unhandled error in Deferred:
May 25 16:35:45 smpp-prod3 jasmind[13382]: Unhandled error in Deferred:
```

Is this a bug or down to some misconfiguration

**Comment by farirat** [comment]
It is an uncatched exception, Jasmin is receiving a pdu with an unknown sequence number, not sure if this is causing a mess for your case ?

**Comment by terrycain** [comment]
I'm not entirely sure if it is affecting anything, I get more `Unhandled error in Deferred:` than stack traces though so not sure if that's related. Would it be better to catch that and log it out?
