### ISSUE TITLE
jasmind: Unhandled Error when accessing user list via PB API

### ISSUE THREAD

**Issue by mexicarne** [jookies/jasmin#719]
Hello, from some time we getting the traceback instead of users list while access it via Perspective Broker API. Here is the isolated sample code that worked earlier:

```python
from twisted.internet import reactor, defer
from jasmin.routing.proxies import RouterPBProxy


http_settings = ("127.0.0.1", 8988, "radmin", "rpwd")


@defer.inlineCallbacks
def test():
    try:
        httpapi = RouterPBProxy()
        yield httpapi.connect(*http_settings)

        users = yield httpapi.user_get_all()
        print("Pickled users: {}".format(users))

        yield httpapi.disconnect()
    except Exception as exc:
        print("FAILED: {}".format(str(exc)))
    finally:
        reactor.stop()


if __name__ == "__main__":
    test()
    reactor.run()

```

Here is the exception:
```python
FAILED: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]
```

and here is the traceback I've got in syslog:
```python
Feb 18 10:43:15 jasmax jasmind[16084]: Unhandled Error
Feb 18 10:43:15 jasmax jasmind[16084]: Traceback (most recent call last):
Feb 18 10:43:15 jasmax jasmind[16084]:   File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
Feb 18 10:43:15 jasmax jasmind[16084]:     return callWithContext({"system": lp}, func, *args, **kw)
Feb 18 10:43:15 jasmax jasmind[16084]:   File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
Feb 18 10:43:15 jasmax jasmind[16084]:     return context.call({ILogContext: newCtx}, func, *args, **kw)
Feb 18 10:43:15 jasmax jasmind[16084]:   File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
Feb 18 10:43:15 jasmax jasmind[16084]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
Feb 18 10:43:15 jasmax jasmind[16084]:   File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
Feb 18 10:43:15 jasmax jasmind[16084]:     return func(*args,**kw)
Feb 18 10:43:15 jasmax jasmind[16084]: --- <exception caught here> ---
Feb 18 10:43:15 jasmax jasmind[16084]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
Feb 18 10:43:15 jasmax jasmind[16084]:     why = selectable.doRead()
Feb 18 10:43:15 jasmax jasmind[16084]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 209, in doRead
Feb 18 10:43:15 jasmax jasmind[16084]:     return self._dataReceived(data)
Feb 18 10:43:15 jasmax jasmind[16084]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 215, in _dataReceived
Feb 18 10:43:15 jasmax jasmind[16084]:     rval = self.protocol.dataReceived(data)
Feb 18 10:43:15 jasmax jasmind[16084]:   File "/usr/lib/python2.7/dist-packages/twisted/spread/banana.py", line 243, in dataReceived
Feb 18 10:43:15 jasmax jasmind[16084]:     gotItem(item)
Feb 18 10:43:15 jasmax jasmind[16084]:   File "/usr/lib/python2.7/dist-packages/twisted/spread/banana.py", line 167, in gotItem
Feb 18 10:43:15 jasmax jasmind[16084]:     self.callExpressionReceived(item)
Feb 18 10:43:15 jasmax jasmind[16084]:   File "/usr/lib/python2.7/dist-packages/twisted/spread/banana.py", line 130, in callExpressionReceived
Feb 18 10:43:15 jasmax jasmind[16084]:     self.expressionReceived(obj)
Feb 18 10:43:15 jasmax jasmind[16084]:   File "/usr/lib/python2.7/dist-packages/twisted/spread/pb.py", line 563, in expressionReceived
Feb 18 10:43:15 jasmax jasmind[16084]:     method(*sexp[1:])
Feb 18 10:43:15 jasmax jasmind[16084]:   File "/usr/lib/python2.7/dist-packages/twisted/spread/pb.py", line 875, in proto_message
Feb 18 10:43:15 jasmax jasmind[16084]:     self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
Feb 18 10:43:15 jasmax jasmind[16084]:   File "/usr/lib/python2.7/dist-packages/twisted/spread/pb.py", line 916, in _recvMessage
Feb 18 10:43:15 jasmax jasmind[16084]:     self._sendAnswer(netResult, requestID)
Feb 18 10:43:15 jasmax jasmind[16084]:   File "/usr/lib/python2.7/dist-packages/twisted/spread/pb.py", line 924, in _sendAnswer
Feb 18 10:43:15 jasmax jasmind[16084]:     self.sendCall("answer", requestID, netResult)
Feb 18 10:43:15 jasmax jasmind[16084]:   File "/usr/lib/python2.7/dist-packages/twisted/spread/pb.py", line 584, in sendCall
Feb 18 10:43:15 jasmax jasmind[16084]:     self.sendEncoded(exp)
Feb 18 10:43:15 jasmax jasmind[16084]:   File "/usr/lib/python2.7/dist-packages/twisted/spread/banana.py", line 314, in sendEncoded
Feb 18 10:43:15 jasmax jasmind[16084]:     self._encode(obj, io.write)
Feb 18 10:43:15 jasmax jasmind[16084]:   File "/usr/lib/python2.7/dist-packages/twisted/spread/banana.py", line 326, in _encode
Feb 18 10:43:15 jasmax jasmind[16084]:     self._encode(elem, write)
Feb 18 10:43:15 jasmax jasmind[16084]:   File "/usr/lib/python2.7/dist-packages/twisted/spread/banana.py", line 355, in _encode
Feb 18 10:43:15 jasmax jasmind[16084]:     "string is too long to send (%d)" % (len(obj),))
Feb 18 10:43:15 jasmax jasmind[16084]: twisted.spread.banana.BananaError: string is too long to send (656274)
```
Any clues what can it be and how to overcome that?

**Comment by mexicarne** [comment]
Needed to say that other user management methods (like `user_add`, `user_set_quota`, `user_remove` etc) working fine. So it looks like the message `twisted.spread.banana.BananaError: string is too long to send (656274)` is related to growing number of jasmin users.

**Comment by mexicarne** [comment]
It looks like we encountered this limit:
https://twistedmatrix.com/documents/16.1.0/core/howto/pb-limits.html

**Comment by farirat** [comment]
I confirm, that's the limit on twisted side, i suggest you build your integration on top of jcli, there's an API wrapper already: https://github.com/jookies/jasmin-api
It's not maitained but you can take the design approach.
