### ISSUE TITLE
jcli: crash upon requesting user list

### ISSUE THREAD

**Issue by mexicarne** [jookies/jasmin#720]
Hello, 

I'm trying to access user list via jcli. Here is how it looks like:
```
Username: jcliadmin
Password: 
Welcome to Jasmin 0.9.27 console
Type help or ? to list commands.

Session ref: 2
jcli : user -lConnection closed by foreign host.
```
And here is the traceback in syslog:
```python
Feb 18 11:01:15 jasmax jasmind[27756]: Unhandled Error
Feb 18 11:01:15 jasmax jasmind[27756]: Traceback (most recent call last):
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
Feb 18 11:01:15 jasmax jasmind[27756]:     return callWithContext({"system": lp}, func, *args, **kw)
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
Feb 18 11:01:15 jasmax jasmind[27756]:     return context.call({ILogContext: newCtx}, func, *args, **kw)
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
Feb 18 11:01:15 jasmax jasmind[27756]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
Feb 18 11:01:15 jasmax jasmind[27756]:     return func(*args,**kw)
Feb 18 11:01:15 jasmax jasmind[27756]: --- <exception caught here> ---
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
Feb 18 11:01:15 jasmax jasmind[27756]:     why = selectable.doRead()
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 209, in doRead
Feb 18 11:01:15 jasmax jasmind[27756]:     return self._dataReceived(data)
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 215, in _dataReceived
Feb 18 11:01:15 jasmax jasmind[27756]:     rval = self.protocol.dataReceived(data)
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/twisted/conch/telnet.py", line 589, in dataReceived
Feb 18 11:01:15 jasmax jasmind[27756]:     self.applicationDataReceived(''.join(appDataBuffer))
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/twisted/conch/telnet.py", line 898, in applicationDataReceived
Feb 18 11:01:15 jasmax jasmind[27756]:     self.protocol.dataReceived(bytes)
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/twisted/conch/telnet.py", line 940, in dataReceived
Feb 18 11:01:15 jasmax jasmind[27756]:     self.protocol.dataReceived(data)
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/twisted/conch/insults/insults.py", line 435, in dataReceived
Feb 18 11:01:15 jasmax jasmind[27756]:     self.terminalProtocol.keystrokeReceived(ch, None)
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/twisted/conch/recvline.py", line 201, in keystrokeReceived
Feb 18 11:01:15 jasmax jasmind[27756]:     m()
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/twisted/conch/recvline.py", line 331, in handle_RETURN
Feb 18 11:01:15 jasmax jasmind[27756]:     return RecvLine.handle_RETURN(self)
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/twisted/conch/recvline.py", line 259, in handle_RETURN
Feb 18 11:01:15 jasmax jasmind[27756]:     self.lineReceived(line)
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/jasmin/protocols/cli/jcli.py", line 87, in lineReceived
Feb 18 11:01:15 jasmax jasmind[27756]:     return CmdProtocol.lineReceived(self, line)
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/jasmin/protocols/cli/protocol.py", line 159, in lineReceived
Feb 18 11:01:15 jasmax jasmind[27756]:     return func(arg)
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/jasmin/protocols/cli/options.py", line 88, in new_func
Feb 18 11:01:15 jasmax jasmind[27756]:     return func(instance, arg, opts)
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/jasmin/protocols/cli/jcli.py", line 174, in do_user
Feb 18 11:01:15 jasmax jasmind[27756]:     self.managers['user'].list(arg, opts)
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/jasmin/protocols/cli/usersm.py", line 427, in list
Feb 18 11:01:15 jasmax jasmind[27756]:     str(throughput).ljust(8)), prompt=False)
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/jasmin/protocols/cli/protocol.py", line 102, in sendData
Feb 18 11:01:15 jasmax jasmind[27756]:     self.terminal.write(data)
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/twisted/conch/insults/insults.py", line 766, in write
Feb 18 11:01:15 jasmax jasmind[27756]:     self.transport.write('\r\n'.join(bytes.split('\n')))
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/twisted/conch/telnet.py", line 815, in write
Feb 18 11:01:15 jasmax jasmind[27756]:     self.transport.write(bytes.replace('\n', '\r\n'))
Feb 18 11:01:15 jasmax jasmind[27756]:   File "/usr/lib/python2.7/dist-packages/twisted/conch/telnet.py", line 901, in write
Feb 18 11:01:15 jasmax jasmind[27756]:     ProtocolTransportMixin.write(self, data.replace('\xff','\xff\xff'))
Feb 18 11:01:15 jasmax jasmind[27756]: exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)```

**Comment by farirat** [comment]
Hello @mexicarne 

Is this a duplicate of #719 ?

Did you make a fresh install or an upgrade to 0.9.27, if the latter, from which version ?

**Comment by mexicarne** [comment]
@farirat Nope, they are different issues. jcli failed to list users since upgrade from 0.9.25 if I recall correctly. But since we dont't use it much, we didn't reacted until now. 

#719 - is a fresh one, that happened out of nowhere. No upgrades or settings changes were done.

**Comment by farirat** [comment]
There maybe some user data that failed to migrate from 0.9.25 to 0.9.27, can't be sure of what it can be but i'm interested to dig in further to provide a fix for the automatic migrator.

Please share any information that can help.

**Comment by mexicarne** [comment]
Ok, I'll try to create some minimal example that breaks the things by cutting non-relevant data from users file.
