### ISSUE TITLE
SMPP connection established from 127.0.0.1 to port 2775

### ISSUE THREAD

**Issue by zouhirmahjoubi** [jookies/jasmin#836]
any help plz!
**default-smpps_01.log**
2020-02-23 23:56:51 WARNING  8413 SMPP connection established from 127.0.0.1 to port 2775
2020-02-23 23:56:51 DEBUG    8413 SMPP Server received PDU from system 'None' [command: bind_transceiver, seq_number: 1, command_status: ESME_ROK]
2020-02-23 23:56:51 DEBUG    8413 Complete PDU dump: PDU [command: bind_transceiver, sequence_number: 1, command_status: ESME_ROK
system_id: 'KOIUJ14'
password: 'pass0123'
system_type: 'OTA'
interface_version: 52
addr_ton: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f04001b1890>, 6, 'INTERNATIONAL')
addr_npi: EnumValue(<jasmin.vendor.enum.Enum object at 0x7f04001b18d0>, 9, 'ISDN')
address_range: ''
]
2020-02-23 23:56:51 DEBUG    8413 From host 127.0.0.1 and using password: pass0123
2020-02-23 23:56:51 WARNING  8413 SMPP Bind request failed for username: "KOIUJ14", reason: Authentication credentials invalid
2020-02-23 23:56:51 DEBUG    8413 Sending PDU: PDU [command: bind_transceiver_resp, sequence_number: 1, command_status: ESME_RINVPASWD
]
2020-02-23 23:56:51 DEBUG    8413 Sending data [00000010800000090000000e00000001]
2020-02-23 23:56:51 DEBUG    8413 SMPP connection attempt failed without binding.
2020-02-23 23:56:51 WARNING  8413 SMPP 127.0.0.1 disconnected from port 2775: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.

**Comment by zouhirmahjoubi** [comment]
hi any one

**Comment by magojr** [comment]
The answer is in the question: "reason: Authentication credentials invalid"
I suggest you to check username/pawwrord and verify the user has been created, activated and has the right to do the operation:
[https://jasmin.readthedocs.io/en/latest/management/jcli/modules.html#user-manager](https://jasmin.readthedocs.io/en/latest/management/jcli/modules.html#user-manager)

**Comment by zouhirmahjoubi** [comment]
i think i found the prob 

### redis-client.log

2020-03-02 18:36:25 INFO     3147 Lost connection.  Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
]
2020-03-02 18:36:25 INFO     3147 Lost connection.  Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
]
2020-03-02 18:36:25 INFO     3147 Lost connection.  Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
]
2020-03-02 18:36:25 INFO     3147 Lost connection.  Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
]
2020-03-02 18:36:25 INFO     3147 Lost connection.  Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
]
2020-03-02 18:36:25 INFO     3145 Lost connection.  Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
]
2020-03-02 18:36:25 INFO     3145 Lost connection.  Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
]
2020-03-02 18:36:25 INFO     3145 Lost connection.  Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
]
2020-03-02 18:36:25 INFO     3145 Lost connection.  Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
]
2020-03-02 18:36:25 INFO     3145 Lost connection.  Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
]
2020-03-02 18:36:25 INFO     3145 Lost connection.  Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
]
2020-03-02 18:36:25 INFO     3145 Lost connection.  Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
]
2020-03-02 18:36:25 INFO     3145 Lost connection.  Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.

**Comment by zouhirmahjoubi** [comment]
can any one explaine what  happening!!!!!
am failed....?
### sudo pip install --pre python-jasmin
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting python-jasmin
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/python-jasmin/

**Comment by zouhirmahjoubi** [comment]
finally my smpps is work ; i set  whitelisting rules ;
but smppc still have problem
 2020-03-09 21:50:01 INFO     4549 Reconnecting after 10 seconds ...
2020-03-09 21:50:11 INFO     4549 Connecting to IPv4Address(TCP, '3.233.206.206', 2775) ...
2020-03-09 21:50:28 ERROR    4549 Connection failed. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.TimeoutError'>: User timeout caused connection failure.
]
2020-03-09 21:50:28 INFO     4549 Reconnecting after 10 seconds ...
2020-03-09 21:50:38 INFO     4549 Connecting to IPv4Address(TCP, '3.233.206.206', 2775) ...
2020-03-09 21:50:41 ERROR    4549 Connection failed. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.TimeoutError'>: User timeout caused connection failure.
]
2020-03-09 21:50:41 INFO     4549 Reconnecting after 10 seconds ...
2020-03-09 21:50:51 INFO     4549 Connecting to IPv4Address(TCP, '3.233.206.206', 2775) ...
2020-03-09 21:51:08 ERROR    4549 Connection failed. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.TimeoutError'>: User timeout caused connection failure.
]
2020-03-09 21:51:08 INFO     4549 Reconnecting after 10 seconds ...
2020-03-09 21:51:18 INFO     4549 Connecting to IPv4Address(TCP, '3.233.206.206', 2775) ...
2020-03-09 21:51:21 ERROR    4549 Connection failed. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.TimeoutError'>: User timeout caused connection failure.
]
2020-03-09 21:51:21 INFO     4549 Reconnecting after 10 seconds ...
2020-03-09 21:51:31 INFO     4549 Connecting to IPv4Address(TCP, '3.233.206.206', 2775) ...
2020-03-09 21:51:48 ERROR    4549 Connection failed. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.TimeoutError'>: User timeout caused connection failure.
]
2020-03-09 21:51:48 INFO     4549 Reconnecting after 10 seconds ...
2020-03-09 21:51:58 INFO     4549 Connecting to IPv4Address(TCP, '3.233.206.206', 2775) ...
2020-03-09 21:52:01 ERROR    4549 Connection failed. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.TimeoutError'>: User timeout caused connection failure.

**Comment by zouhirmahjoubi** [comment]
also redis client work when with httpc
whan i try to send sms with http api it show me ok is sent but am not receive any think my phone , 
is smppc the problem or what!!

2020-03-09 21:48:33 INFO     4549 Connection made
2020-03-09 21:51:39 DEBUG    4549 Executing redis command: ('HMSET', 'dlr:c7e88deb-3984-4941-89ea-5fec3155cecc', 'level', 2, 'url', 'http://34.204.142.92/playsms/plugin/gateway/jasmin/callback.php', 'expiry', 86400, 'connector', 'vino', 'sc', 'httpapi', 'method', 'POST')
