### ISSUE TITLE
Try to use jasmin with USSDC

### ISSUE THREAD

**Issue by npokasub** [jookies/jasmin#842]
2020-03-22 19:50:31 ERROR    9543 Optional Parameter not allowed: Optional param ussd_service_op unknown
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/twisted/protocol.py", line 195, in rawMessageReceived
    pdu = self.encoder.decode(StringIO.StringIO(message))
  File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1023, in decode
    self.decodeBody(file, pdu, headerParams['command_length'] - self.HEADER_LEN)
  File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1069, in decodeBody
    optionalParams = self.decodeOptionalParams(pdu.optionalParams, file, bodyLength - mParamsLen)
  File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 1156, in decodeOptionalParams
    option = self.optionEncoder.decode(file)
  File "/usr/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_encoding.py", line 908, in decode
    raise PDUParseError("Optional param %s unknown" % tag, pdu_types.CommandStatus.ESME_ROPTPARNOTALLWD)
PDUParseError: Optional Parameter not allowed: Optional param ussd_service_op unknown
2020-03-22 19:50:31 CRITICAL 9543 Received unparsable PDU 0000004400000005000000000000000250320001013636393737303931323035000101363639323330313131323100000000000000000f00062a34303036230501000101

**Comment by farirat** [comment]
Jasmin can not handle USSD operations over smpp.
