### ISSUE TITLE
enum module conflicting with enum34

### ISSUE THREAD

**Issue by fourat** [jookies/jasmin#93]
enum as a jasmin install requirement and enum34 as a cryptography install requirement provide the same module name ***enum***, this will lead to errors:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/trial/runner.py", line 498, in loadPackage
    module = modinfo.load()
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/reflect.py", line 303, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/reflect.py", line 242, in _importAndCheckStack
    return __import__(importName)
  File "/home/travis/build/fourat/jasmin/jasmin/managers/test/test_managers.py", line 13, in <module>
    from jasmin.managers.clients import SMPPClientManagerPB
  File "/home/travis/build/fourat/jasmin/jasmin/managers/clients.py", line 8, in <module>
    from jasmin.protocols.smpp.services import SMPPClientService
  File "/home/travis/build/fourat/jasmin/jasmin/protocols/smpp/services.py", line 2, in <module>
    from jasmin.protocols.smpp.factory import SMPPClientFactory
  File "/home/travis/build/fourat/jasmin/jasmin/protocols/smpp/factory.py", line 7, in <module>
    from jasmin.protocols.smpp.protocol import SMPPClientProtocol, SMPPServerProtocol
  File "/home/travis/build/fourat/jasmin/jasmin/protocols/smpp/protocol.py", line 6, in <module>
    from jasmin.vendor.smpp.twisted.protocol import SMPPClientProtocol as twistedSMPPClientProtocol
  File "/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/twisted/protocol.py", line 21, in <module>
    from jasmin.vendor.smpp.pdu.operations import *
  File "/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/operations.py", line 16, in <module>
    from jasmin.vendor.smpp.pdu.pdu_types import CommandId, PDU, PDURequest, PDUResponse, PDUDataRequest
  File "/usr/local/lib/python2.7/dist-packages/jasmin/vendor/smpp/pdu/pdu_types.py", line 23, in <module>
    CommandId = Enum(*constants.command_id_name_map.keys())
exceptions.TypeError: __call__() takes at most 5 arguments (28 given)

**Comment by fourat** [comment]
A proposed solution is to venodrize enum module and remove it as an external requirement.
