### ISSUE TITLE
Remote redis server with password

### ISSUE THREAD

**Issue by bandiphani** [jookies/jasmin#991]
Hi Jasmin team.. 
I am trying to connect remote redis server with password from Jasmin (docker).. getting below error... kindly help me to resolve the issue

```
jasmin       | Unhandled error in Deferred:
jasmin       |
jasmin       | Traceback (most recent call last):
jasmin       |   File "/usr/local/lib/python3.9/site-packages/txredisapi.py", line 528, in replyReceived
jasmin       |     self.replyQueue.put(reply)
jasmin       |   File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 1872, in put
jasmin       |     self.waiting.pop(0).callback(obj)
jasmin       |   File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 460, in callback
jasmin       |     self._startRunCallbacks(result)
jasmin       |   File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
jasmin       |     self._runCallbacks()
jasmin       | --- <exception caught here> ---
jasmin       |   File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
jasmin       |     current.result = callback(current.result, *args, **kw)
jasmin       |   File "/usr/local/lib/python3.9/site-packages/txredisapi.py", line 533, in handle_reply
jasmin       |     raise r
jasmin       | txredisapi.ResponseError: NOAUTH Authentication required.
jasmin       |

```
thanks..
phani

**Comment by lauer** [comment]
For me it helped to set the `dbid = 0` inside jasmin.cfg

    [redis-client]
    host=jasmin-redis-master.jasmin.svc
    dbid = 0
    password = VerySecret

I got the same error if I only set the password.
